# Generated by Django 4.2.1 on 2023-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('spam_score', models.FloatField()),
                ('phishing_score', models.FloatField()),
                ('fake_news_score', models.FloatField()),
                ('emotional_score', models.FloatField()),
                ('final_score', models.FloatField()),
            ],
        ),
    ]
