# Generated by Django 4.2 on 2023-05-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_email_emotional_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='emotional_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='url_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
