# Generated by Django 4.2 on 2023-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_email_emotional_score_email_url_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='toxicity_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
