# Generated by Django 4.2 on 2023-05-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_email_toxicity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sentiment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
