# Generated by Django 4.2 on 2023-05-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_email_url_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment_score',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
